# Generated by Django 3.1.7 on 2021-03-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210320_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='date',
            new_name='created_at',
        ),
    ]
