# Generated by Django 3.1.7 on 2021-03-23 19:38
from django.db import migrations


def some_forward_action(apps, schema_editor):
    Product = apps.get_model('app', 'Product')  # Приложение и модель
    Product.objects.create(name='Pizza', text='Vegan-pizza', price=34.5, stock=60)
    Product.objects.create(name='Soup', text='Misso-soup', price=25.8, stock=100)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210320_2140'),
    ]

    operations = [
        migrations.RunPython(some_forward_action, lambda x, y: None)
    ]
