# Generated by Django 3.1.7 on 2021-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210323_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('AS', 'Accepted'), ('Rj', 'Rejected')], default='OP', max_length=2),
        ),
    ]
