# Generated by Django 3.1.7 on 2021-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='money',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=9, verbose_name='Money'),
        ),
    ]
